<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>net481;net10.0-windows</TargetFrameworks>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<UseWindowsForms>true</UseWindowsForms>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<OutputPath>bin\</OutputPath>
	</PropertyGroup>
	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
		<EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
	</PropertyGroup>
	<PropertyGroup>
		<SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
		<NoWarn>$(NoWarn);NU1510;WFO1000</NoWarn>
		<GenerateResourceWarnOnBinaryFormatterUse>false</GenerateResourceWarnOnBinaryFormatterUse>
	</PropertyGroup>

	<ItemGroup Condition=" $(targetframework.startswith('net48')) ">
		<ProjectReference Include="..\System.Windows.Forms\System.Windows.Forms.Legacy.csproj" >
			<Aliases>overlap</Aliases>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
		<ProjectReference Include="..\System.Windows.Forms\System.Windows.Forms.Legacy.csproj" />
	</ItemGroup>
			
	<ItemGroup>
		<None Update="Data\Authors.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\Books.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\invoices.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>